project_id = "mvlhtcdurcfiammzcvfv"

[functions.kiwify-webhook]
verify_jwt = false

[functions.resend-all-welcome-emails]
verify_jwt = true

[functions.generate-carousel]
verify_jwt = true

[functions.generate-carousel-copy]
verify_jwt = true

[functions.generate-video]
verify_jwt = true

[functions.check-limits]
verify_jwt = true

[functions.profile-analysis]
verify_jwt = true

[functions.parse-pdf]
verify_jwt = true

[functions.creative-engine]
verify_jwt = true

[functions.generate-copy]
verify_jwt = true

[functions.compose-creative]
verify_jwt = true

[functions.suggest-safe-prompt]
verify_jwt = true

[functions.create-multiple-users]
verify_jwt = true

[functions.revoke-unauthorized-access]
verify_jwt = true

