export interface FileAttachment {
  id: string;
  name: string;
  type: string;
  size: number;
  url: string;
  preview?: string; // base64 for display
}

export interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: number;
  images?: string[]; // base64 images for OpenAI
  attachments?: FileAttachment[]; // stored file references
  transcript?: string; // voice transcription
  isVoiceMessage?: boolean; // flag for voice messages
  voiceTimestamp?: number; // timestamp for voice message timing
  generatedImages?: string[]; // base64 images generated by AI
  agentId?: string; // which agent generated the message
}

export interface Conversation {
  id: string;
  title: string;
  messages: Message[];
  createdAt: number;
  updatedAt: number;
  agentId?: string; // primary agent of the conversation
}

export interface LumiModule {
  id: string;
  title: string;
  icon: string;
  prompts: string[];
  color: string;
}

export interface LumiSettings {
  sidebarOpen: boolean;
  theme: 'light' | 'dark';
}

export interface LumiStore {
  conversations: Conversation[];
  settings: LumiSettings;
}